# Generated by Django 5.0.4 on 2024-04-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
